### ISSUE TITLE
Investigate mento-sdk error handling

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-sdk#23]
**Description**

We need to look into how we can better handle smart contract reverts and display errors that may be thrown when using the SDK. We should look into the following:

- Extracting the revert reason from gas estimation 
- Mapping revert reasons to user friendly custom errors

**Acceptance Criteria**

- [ ] We have a clear idea of how to extract the revert reason from an error and map this to a user-friendly format

**Comment by bayological** [comment]
We can do the following in functions that return a transaction request:
- Modify the function to do a pre-transaction simulation using [estimate gas](https://docs.ethers.org/v5/api/providers/provider/#Provider-estimateGas). The actual estimate can be discarded, but the call can be wrapped in a try/catch to detect failure. 
- When we get a failure, the outer exception will have an error with the message cannot estimate gas. The inner exception should be a reason with the string revert message from our contracts. We need to add a helper function to extract this reason from any error and a fallback message in case the revert message cannot be extracted.
- We should also consider adding an optional flag that defaults to true but can be overridden to determine whether or not the simulation should be done to give some flexibility to consumers

I think mapping revert reasons to friendly messages may be excessive. The revert reasons in our contracts are pretty self-explanatory but we also have a lot of messages. Creating a mapping for each of these reasons would be a lot.

**Comment by nvtaveras** [comment]
@bayological SGTM! And regarding the mapping, maybe we can some of the the most relevant ones like circuit breaker tripped, trading limit exceeded, amountOut/In not enough?

**Comment by bayological** [comment]
@nvtaveras I created [this issue](https://github.com/mento-protocol/mento-sdk/issues/25). On the mapping, we could do that, but how do you see this being implemented? This would be more involved, but we can map something like "L1 Exceeded" to "Trading limit 1 for cUSD has been hit for this exchange". We'll need to have additional logic to determine the token, but we would have all that information available.
